baseURL = 'https://whyuhurtz.me/'
title = "whyuhurtz's Blog"
theme = 'LoveIt'
copyright = '&copy; 2023-2025'

defaultContentLanguage = "en"
languageName = "English"
languageCode = 'en-us'
hasCJKLanguage = false

enableRobotsTXT = true
enableGitInfo = false
enableEmoji = true

[pagination]
  disableAliases = false
  pagerSize = 10
  path = "page"

[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
  [[menu.main]]
    weight = 2
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
  [[menu.main]]
    weight = 3
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
  [[menu.main]]
    weight = 4
    identifier = "achievements"
    name = "Achievements"
    url = "/achievements/"
  [[menu.main]]
    weight = 5
    identifier = "about"
    name = "About"
    url = "/about/"

[params]
  defaultTheme = "auto"
  dateFormat = "2006-01-02"
  title = "whyuhurtz's Blog"

  [params.author]
    name = "whyuhurtz"
    email = "wahyupriambodo.sec@gmail.com"
    link = "https://github.com/whyuhurtz"
  
  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"

    [params.header.title]
      name = "whyuhurtz's Blog"
      typeit = false
  
  [params.footer]
    enable = true
    hugo = false
    author = false
    copyright = true
    since = 2023
  
  [params.section]
    paginate = 20
    dateFormat = "01-02"
    rss = 10
  
  [params.app]
    title = "whyuhurtz's Blog"
    noFavicon = false
  
  [params.list]
    paginate = 20
    dateFormat = "01-02"
  
  [params.analytics]
    [params.analytics.google]
      id = "G-LHYL3DDVEV"
      respectDoNotTrack = false
  
  [params.search]
    enable = false
    # type = "algolia"
    # contentLength = 4000
    # placeholder = "Search posts..."
    # maxResultLength = 10
    # highlightTag = "em"
    # absoluteURL = false
    # [params.search.algolia]
      # index = "whyuhurtz_me_45t4qzqypw_pages"
      # appID = "45T4QZQYPW"
      # searchKey = "e181db5a82cb99d24dfa035720d0dd52"
  
  [params.home]
    rss = 10

    [params.home.profile]
      enable = true
      avatarURL = "/images/avatar.jpg"
      title = "whyuhurtz{h3ll0_w0rld_4nd_h4v3_4_n1c3_d4y}"
      subtitle = "Just an ordinary cybersec guy."
      social = true
      typeit = true
    
    [params.home.posts]
      enable = true
      paginate = 10
  
  [params.social]
    GitHub = "whyuhurtz"
    Linkedin = "wahyu-priambodo"
    Instagram = "whyuhurtz"
    Email = "wahyupriambodo.sec@gmail.com"
  
  [params.page]
    hiddenFromHomePage = false
    lightgallery = true
    fontawesome = true
    linkToMarkdown = false
    rssFullText = false

    [params.page.toc]
      enable = true
      keepStatic = false
      auto = true
    
    [params.page.code]
      copy = true
      maxShownLines = 500
      [params.page.code.render]
        goat = true
        mermaid = true
    
    [params.page.math]
      enable = true
      copyTex = true
    
    [params.page.share]
      enable = false
    
    [params.page.comment]
      enable = false

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
  
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
  
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[permalinks]
  posts = ":year/:month/:slug"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
